{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ngrinder",
    "module": "ngrinder-groovy",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "icugm7oe5jh7xhimqrghenax54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.0.jar",
          "url": "ngrinder-groovy-3.5.0.jar",
          "size": 43144,
          "sha512": "7b2cea556ad2fcb8496a7d7fc852822d107ccf04eddfba7a292529f1c94f06f1dfce5234ac2055b4770d9d0e72204bdd06dcae3731d6fc9227caf82230c33909",
          "sha256": "58ef579d9740eb7f44ae71edc0f42ef520f185f282533f287ca8b3741979329f",
          "sha1": "f77dea4864ff05076ee614f2c75365945c5bdf6f",
          "md5": "ff88339777c8ed827ee788dd74fd33cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.0.jar",
          "url": "ngrinder-groovy-3.5.0.jar",
          "size": 43144,
          "sha512": "7b2cea556ad2fcb8496a7d7fc852822d107ccf04eddfba7a292529f1c94f06f1dfce5234ac2055b4770d9d0e72204bdd06dcae3731d6fc9227caf82230c33909",
          "sha256": "58ef579d9740eb7f44ae71edc0f42ef520f185f282533f287ca8b3741979329f",
          "sha1": "f77dea4864ff05076ee614f2c75365945c5bdf6f",
          "md5": "ff88339777c8ed827ee788dd74fd33cd"
        }
      ]
    }
  ]
}
