{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ngrinder",
    "module": "ngrinder-core",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "pgg4cakxejclnlyd52rtmrztqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.ngrinder",
          "module": "ngrinder-groovy",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.fusesource",
          "module": "sigar",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "commons-collections",
          "module": "commons-collections",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.python",
          "module": "jython-standalone",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.32"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.3.11.Final"
          }
        },
        {
          "group": "org.jboss.spec.javax.transaction",
          "module": "jboss-transaction-api_1.2_spec",
          "version": {
            "requires": "1.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-core-3.5.0.jar",
          "url": "ngrinder-core-3.5.0.jar",
          "size": 710529,
          "sha512": "505d9f02782483c97907d8447a0a2715806e97a0eb265b61e35ab586b65601e36902e6a0112927d40df1d4a4019254009233b83c070bd55b9115965853c1f8d2",
          "sha256": "fd2ec6edd6120c90789560c7c471c6bb86e5f36c8650beb5b966682f7b1d862d",
          "sha1": "bd75f12fa23aca32beb40c7fa80137521bace86c",
          "md5": "f1eaa8c6f514b05202ecd3a3aa0db9ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.ngrinder",
          "module": "ngrinder-groovy",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.fusesource",
          "module": "sigar",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "commons-collections",
          "module": "commons-collections",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.python",
          "module": "jython-standalone",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.32"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.3.11.Final"
          }
        },
        {
          "group": "org.jboss.spec.javax.transaction",
          "module": "jboss-transaction-api_1.2_spec",
          "version": {
            "requires": "1.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-core-3.5.0.jar",
          "url": "ngrinder-core-3.5.0.jar",
          "size": 710529,
          "sha512": "505d9f02782483c97907d8447a0a2715806e97a0eb265b61e35ab586b65601e36902e6a0112927d40df1d4a4019254009233b83c070bd55b9115965853c1f8d2",
          "sha256": "fd2ec6edd6120c90789560c7c471c6bb86e5f36c8650beb5b966682f7b1d862d",
          "sha1": "bd75f12fa23aca32beb40c7fa80137521bace86c",
          "md5": "f1eaa8c6f514b05202ecd3a3aa0db9ed"
        }
      ]
    }
  ]
}
